name: mocki
port: 3000
endpoints:
- path: /fake
  method: get
  responses: - statusCode: 200
  body:
  firstName: !Fake firstName
  lastName: !Fake lastName
  email: !Fake email
  address: !Fake streetAddress
  phone: !Fake phoneNumber
  createdAt: !Fake pastDate
  company: !Fake company
